apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ejemplo-pv-claim
spec:
  storageClassName: azurefile
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-aks
spec:
  selector:
    matchLabels:
      app: nginx-aks
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-aks
    spec:
      volumes: 
        - name: ejemplo-pvc
          persistentVolumeClaim:
            claimName: ejemplo-pv-claim
      containers:
      - name: nginx-aks
        image: javk13.azurecr.io/web_aks:casopractico2
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: ejemplo-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-aks
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx-aks
